		<div id="footer">
			<p><small>Se ve mejor con el navegador Internet Explorer</small><br>
			<a href="/index.shtml">Página principal</a> |
			<a href="/contact/index.shtml">Comuníquese con nosotros</a> | 
			<a href="/about/compacttexans.shtml">Acuerdo con los texanos</a> | 
			<a href="/news/SitePolicies/sitepolicies.shtml">Normas del sitio</a> | 
			<a href="http://www.texashomelandsecurity.com/">Seguridad del Territorio Nacional</a> | 
			<a href="http://www2.tsl.state.tx.us/trail/">Búsqueda estatal</a>  | 
			<a href="http://www.state.tx.us/">Texas Online</a>  | 
			<a href="/about/viewing.shtml">Información del visualizador de archivos</a></p>
			<div id="footer_curve_wrapper">
				<div id="footer_lcb">&nbsp;</div>
				<div id="footer_rcb">&nbsp;</div>
			</div><!-- end footer_curve_wrapper -->
		</div><!-- end footer -->