<div id="header">
	<div id="header_curve_wrapper">
		<div id="headerlc"> </div>
		<div id="headerrc"> </div>
	</div>	
	<div id="headertop"> 
		<a href="/index.shtml" title="DARS Home" ><img src="/images/DARSbanner.gif" alt="Department of Assistive and Rehabilitative Services" /></a>
	</div><!--end headertop -->
		<div id="skipnav">
			<a href="#StartContent" style="text-decoration: none;">Saltar al contenido</a></p></p>
			<a href="javascript:fontsizeup();" style="text-decoration: none;" title="Increase Font Size">Font Size +</a></p>
			<a href="javascript:fontsizedown();" style="text-decoration: none;" title="Decrease Font Size">Font Size -</a> 
		</div><!-- end skipnav -->
	<div id="GlobalNav">
		<div class="menuContainer">
			<ul class="mainMenu" id="navItem"> <!-- change back to name -->


 


			<li><a href="/services/index.shtml" class="navItem">Find Services</a>
			<ul class="navMenu">
			<li><a href="/drs/index.shtml" class="navItem"><strong>Rehabilitation Services</strong></a></li>	

			<li><a href="http://www.dars.state.tx.us/drs/crs.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Comprehensive Rehabilitation </p>&nbsp;&nbsp;&nbsp;&nbsp; Services</a></li>
			<li><a href="http://www.dars.state.tx.us/dhhs/index.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Deaf &amp; Hard of Hearing Services</a></li>
			<li><a href="http://www.dars.state.tx.us/drs/il.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Independent Living Services &amp;</p>&nbsp;&nbsp;&nbsp;&nbsp;  Centers</a></li>
			<li><a href="http://www.dars.state.tx.us/drs/RehabTechLab.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rehab Technology Resource Center</a></li>
			<li><a href="http://www.dars.state.tx.us/dhhs/stap.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Specialized Telecommunications</p>&nbsp;&nbsp;&nbsp;&nbsp; Assistance Program</a></li>
			<li><a href="http://www.dars.state.tx.us/drs/vr.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Vocational Rehabilitation</a></li>
												
					
			<li><a href="/dbs/index.shtml" class="navItem"><strong>Blind Services</strong></a></li>


			<li><a href="http://www.dars.state.tx.us/dbs/bcp.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Blind Children&#39;s Vocational </p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Discovery &amp; Development</a></li>
			<li><a href="http://www.dars.state.tx.us/dbs/best/index.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Blindness Education Screening &amp;</p>&nbsp;&nbsp;&nbsp;&nbsp; Treatment</a></li>
			<li><a href="http://www.dars.state.tx.us/dbs/bet/index.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Business Enterprises of Texas</a></li>
			<li><a href="http://www.dars.state.tx.us/dbs/ccrc/index.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Criss Cole Rehabilitation Center</a></li>
			<li><a href="http://www.dars.state.tx.us/dbs/il.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Independent Living Services</a></li>
			<li><a href="http://www.dars.state.tx.us/dbs/vr.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Vocational Rehabilitation</a></li>


			<li><a href="/ecis/index.shtml" class="navItem"><strong>Early Childhood Intervention Services</strong></a></li>				
			<li><a href="/services/dds.shtml" class="navItem"><strong>Disability Determination Services</strong></a></li>
			<li><a href="/services/agencyservices.shtml" class="navItem"><strong>Help for State Agencies</strong></a></li>
			<li><a href="/services/personalattendants.shtml" class="navItem"><strong>Find a personal attendant</strong></a></li>
			<li><a href="/edc/index.shtml" class="navItem"><strong>Employment &#38; Disability Connections&#47; </p>Medicaid Buy&#45;In</strong></a></li>
                       	<li><a href="/stakeholders/autism/index.shtml" class="navItem"><strong>Autism Program</strong></a></li>
			<li><a href="/supemp/index.shtml" class="navItem"><strong>Find a Supported Employment Provider</strong></a></li>
			<li><a href="/services/servicesforbusiness.shtml" class="navItem"><strong>DARS Services for Business</strong></a></li>					</ul>
				
				</li>




				<li><a href="/news/index.shtml" class="navItem">News &amp; Information</a>
					<ul class="navMenu">
						<li><a href="/about/index.shtml" class="navItem">About DARS</a></li>
						<li><a href="/announcements/index.shtml" class="navItem"> Announcements</a></li>
						<li><a href="/contact/index.shtml" class="navItem">Contact Us</a></li>
						<li><a href="/reports/index.shtml" class="navItem">Data &amp; Reports</a></li>
						<li><a href="/reports/financial.shtml" class="navItem">Financial and Budget Information</a></li>
						<li><a href="https://rm.accesshr.hhsc.state.tx.us/ENG/careerportal/default.cfm?szUniqueCareerPortalID=fbc767e0-795a-412f-8897-431b08f314e8" class="navItem">Jobs</a></li>
						<li><a href="/legislative/legislative.shtml" class="navItem">Legislative Updates</a></li>						
						<li><a href="/contact/visitor.shtml" class="navItem">Maps &amp; Visitor Information</a></li>
						<li><a href="/news/meetings.shtml" class="navItem">Meeting Notices</a></li>
						<li><a href="/publications/index.shtml" class="navItem">Publications</a></li>
						<li><a href="/stakeholders/index.shtml" class="navItem">Stakeholder Relations</a></li>
						</ul>
				</li>




				<li><a href="/rules/index.shtml" class="navItem">Rules &amp; Statutes</a>
					<ul class="navMenu">						
						<li><a href="/rules/index.shtml" class="navItem">Federal/State statutes</a></li>
						<li><a href="/rules/openrecords.shtml" class="navItem">Public Information</a></li>						
						<li><a href="/rules/sitepolicies.shtml" class="navItem">Site Policies</a></li>
					</ul>
				</li>



				<li><a href="/business/index.shtml" class="navItem">Business Information</a>
					<ul class="navMenu">
						<li><a href="/business/contracts.shtml" class="navItem">Contracts</a></li>
						<li><a href="http://www.window.state.tx.us/comptrol/expendlist/expendlist.html" class="navItem">DARS Expenditures</a></li>
						<li><a href="/edc/grants/gvprogram.shtml">DARS Grants and Volunteer Program</a></li>
						<li><a href="/business/index.shtml" class="navItem">Doing Business with DARS</a></li>
						<li><a href="/business/energy.shtml" class="navItem">Energy Consumption</a></li>
						<li><a href="/business/grants.shtml">Grants/Funding Opportunities</a></li>
						<li><a href="/business/hub.shtml" class="navItem">Historically Underutilized Businesses</a></li>
						<li><a href="/business/procurement.shtml" class="navItem">Procurement</a></li>
						<li><a href="http://info.sos.state.tx.us/pls/pub/readtac$ext.TacPage?sl=R&amp;app=9&amp;p_dir=&amp;p_rloc=&amp;p_tloc=&amp;p_ploc=&amp;pg=1&amp;p_tac=&amp;ti=40&amp;pt=2&amp;ch=104&amp;rl=301">Protest Procedures</a></li>
						<li><a href="/business/providers.shtml" class="navItem">Provider &amp; Contractor Information</a></li>
						<li><a href="http://www.window.state.tx.us/wherethemoneygoes">Where The Money Goes</a></li>
					</ul>
				</li>



				<li><a href="/arra/index.shtml" class="navItem">Stimulus (ARRA)</a>
					<ul class="navMenu">
						<li><a href="http://www.recovery.gov/" class="navItem"><strong>ARRA Expense Details</strong></a></li>
						<li><a href="/arra/fedquarterly.shtml" class="navItem"><strong>Federal Quarterly Reports</strong></a></li>
						<li><a href="/arra/fed1stquarter2010.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1st Quarter 2010</a></li>
						<li><a href="/arra/fed2ndquarter2010.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2nd Quarter 2010</a></li>
						<li><a href="/arra/intended_use.pdf" class="navItem"><strong>Intended Use Report</strong></a></li>
						<li><a href="/arra/quarterly.shtml" class="navItem"><strong>LBB Quarterly Reports</strong></a></li>
						<li><a href="/arra/1stquarter2010.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1st Quarter 2010</a></li>
						<li><a href="/arra/2ndquarter2010.shtml" class="navItem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2nd Quarter 2010</a></li>
						<li><a href="/arra/rfp.shtml" class="navItem"><strong>Requests for Proposals</strong></a></li>
						<li><a href="https://sao.fraud.state.tx.us/hotline.aspx" class="navItem"><strong>State Auditor's Fraud Hotline</strong></a></li>
						<li><a href="http://window.state.tx.us/recovery/" class="navItem"><strong>State Comptroller ARRA</strong></a></li>
						<li><a href="http://txstimulusfund.com/Default.aspx" class="navItem"><strong>Texas Stimulus Fund</strong></a></li>
						<li><a href="http://www2.ed.gov/policy/gen/leg/recovery/index.html" class="navItem"><strong>U.S. Dept of Education Stimulus</strong></a></li>


						
<!--

						<li><a href="/arra/quarterly.shtml" class="navItem">Quarterly Reports</a></li>
						<li><a href="Intended_Use_Report.pdf">Intended Use Report</a></li>

						<li>DARS ARRA Plans</li>
						<li>Grant Awards</li>
						<li>DARS ARRA Contract Template</li>
						<li>Buy American/Buy Green</li>
						<li>Quarterly Reports (Accessible Version)</li>
						<li>State Weekly Reports</li>
-->

					</ul>
				</li>





			</ul>
<div id="search_sub" style="vertical-align:middle;">
<form action="/script/search/searchquery.asp" method="post" id="search" style="margin:0;padding:0;text-align:right;">
<P>
<label class="hidden" for="searchFor">Search</label>
<INPUT id="searchFor" style="HEIGHT: 15px" size="10" name="SearchString" title="Search" value="" /> <INPUT style="HEIGHT: 20px" type="submit" name="searchFor" value="Search" />
</P>
</form>

			</div><!-- end search_sub div-->
		</div><!-- end menuContainer div-->
	</div><!-- end GlobalNav id-->
	<a name="StartContent"> </a>
</div><!-- end header div -->