<div id="header">
	<div id="header_curve_wrapper">
		<div id="headerlc"> </div>
		<div id="headerrc"> </div>
	</div>	
	<div id="headertop"> 
		<a href="/index.shtml" title="DARS Home" ><img src="/images/DARSbanner.gif" alt="Department of Assistive and Rehabilitative Services" /></a>
	</div><!--end headertop -->
		<div id="skipnav">
			<a href="#StartContent" style="text-decoration: none;">Saltar al contenido</a></p></p>
			<a href="javascript:fontsizeup();" style="text-decoration: none;" title="Increase Font Size">Font Size +</a></p>
			<a href="javascript:fontsizedown();" style="text-decoration: none;" title="Decrease Font Size">Font Size -</a> 
		</div><!-- end skipnav -->
	<div id="GlobalNav">
		<div class="menuContainer">
<UL id=navItem class=mainMenu><!-- change back to name -->
  <LI><A class=navItem href="http://www.dars.state.tx.us/index.shtml">Página 
  principal</A> 
  <LI><A class=navItem 
  href="http://www.dars.state.tx.us/services/index.shtml">Buscar servicios</A> 
  <UL class=navMenu>
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/drs/index.shtml"><STRONG>Servicios de 
    Rehabilitación</STRONG></A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/drs/crs.shtml">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Servicios 
    de Rehabilitación <BR>&nbsp;&nbsp;&nbsp;&nbsp; Integral</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/dhhs/index.shtml">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Servicios 
    para Personas Sordas y con Problemas de la Audición</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/drs/il.shtml">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Centros 
    y Servicios para la Vida<BR>&nbsp;&nbsp;&nbsp;&nbsp; Independiente</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/drs/RehabTechLab.shtml">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Centro 
    de Recursos de Tecnología de Rehabilitación</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/dhhs/stap.shtml">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Programa 
    de Ayuda con <BR>&nbsp;&nbsp;&nbsp;&nbsp; Telecomunicaciones 
    Especializadas</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/drs/vr.shtml">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rehabilitación 
    Vocacional</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/dbs/index.shtml"><STRONG>Servicios para 
    Personas Ciegas</STRONG></A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/dbs/bcp.shtml">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Programa 
    de Descubrimiento y Desarrollo <BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Vocacional 
    para Niños Ciegos</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/dbs/best/index.shtml">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Programa 
    de Educación, Detección y<BR>&nbsp;&nbsp;&nbsp;&nbsp; Tratamiento de la 
    Ceguera</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/dbs/bet/index.shtml">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Empresas 
    Comerciales de Texas</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/dbs/ccrc/index.shtml">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Centro 
    de Rehabilitación Criss Cole</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/dbs/il.shtml">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Servicios 
    para la Vida Independiente</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/dbs/vr.shtml">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rehabilitación 
    Vocacional</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/ecis/index.shtml"><STRONG>Servicios de 
    Intervención Temprana en la Infancia</STRONG></A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/services/dds.shtml"><STRONG>Servicios de 
    Determinación de Discapacidad</STRONG></A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/services/agencyservices.shtml"><STRONG>Servicios 
    de comunicación para departamentos estatales</STRONG></A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/services/personalattendants.shtml"><STRONG>Encontrar 
    a un ayudante personal</STRONG></A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/stakeholders/autism/index.shtml"><STRONG>Programa 
    de Autismo </STRONG></A>
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/supemp/index.shtml"><STRONG>Encontrar a un 
    proveedor de empleo con apoyo</STRONG></A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/services/servicesforbusiness.shtml"><STRONG>Servicios 
    del DARS para empresas</STRONG></A> </LI></UL>
  <LI><A class=navItem 
  href="http://www.dars.state.tx.us/news/index.shtml">Noticias e información</A> 

  <UL class=navMenu>
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/news/overview.shtml">Acerca del DARS</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/announcements/index.shtml">Anuncios</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/contact/index.shtml">Comuníquese con 
    nosotros</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/news/meetings.shtml">Consejos y comités 
    asesores</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/reports/index.shtml">Datos e informes</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/disability/index.shtml">Concientización 
    sobre la discapacidad</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/reports/financial.shtml">Información 
    financiera y de presupuestos</A> 
    <LI><A class=navItem 
    href="https://jobshrportal.cpa.texas.gov/ENG/careerportal/default.cfm?szUniqueCareerPortalID=fbc767e0-795a-412f-8897-431b08f314e8">Empleo</A> 

    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/legislative/legislative.shtml">Presentaciones 
    legislativas</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/contact/visitor.shtml">Mapas e información 
    para visitantes</A> 
    <LI><A class=navItem 
    href="http://www.hhs.state.tx.us/OfficeNotices.shtml">Avisos sobre cierre de 
    la oficina</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/news/public_information/openrecords.shtml">Información 
    pública</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/publications/index.shtml">Publicaciones</A> 

    <LI><A class=navItem 
    href="https://sao.fraud.state.tx.us/hotline.aspx">Denuncias de fraude</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/news/sitepolicies/SitePolicies.shtml">Normas 
    del sitio</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/stakeholders/index.shtml">Relaciones con 
    las partes interesadas</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/about/index.shtml">Visión y misión</A> 
    </LI></UL>
  <LI><A class=navItem 
  href="http://www.dars.state.tx.us/rules/index.shtml">Reglas y normas</A> 
  <UL class=navMenu>
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/rules/index.shtml">Normas 
    federales/estatales, normas y regulaciones</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/rules/Four-year_Rule_Review.shtml">Revisión 
    de reglas cada cuatro años</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/rules/rules_in_progress.shtml">Reglas 
    propuestas</A> </LI></UL>
  <LI><A class=navItem 
  href="http://www.dars.state.tx.us/business/index.shtml">Información sobre 
  operaciones</A> 
  <UL class=navMenu>
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/business/contracts.shtml">Contratos</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/business/terms.shtml">Términos y 
    condiciones estándar del DARS para adquisiciones</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/business/energy.shtml">Consumo de 
    energía</A> 
    <LI><A 
    href="http://www.dars.state.tx.us/business/contracting-opportunities.shtml">Oportunidades 
    de subvenciones y financiación</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/business/hub.shtml">Empresas 
    Históricamente Subutilizadas</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/business/providers.shtml">Información para 
    proveedores</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/business/procurement.shtml">Licitaciones</A> 

    <LI><A 
    href="http://info.sos.state.tx.us/pls/pub/readtac$ext.TacPage?sl=T&amp;app=2&amp;p_dir=N&amp;p_rloc=83541&amp;p_tloc=&amp;p_ploc=1&amp;pg=37&amp;p_tac=83505&amp;ti=1&amp;pt=15&amp;ch=391&amp;rl=1">Procedimientos 
    de protesta</A> 
    <LI><A class=navItem 
    href="http://www.dars.state.tx.us/arra/index.shtml">Incentivos (ARRA)</A> 
    <LI><A class=navItem href="http://www.texastransparency.org/moneygoes">Dónde 
    va el dinero</A> </LI></UL></LI></UL>
<UL></UL>
<div id="search_sub" style="vertical-align:middle;">
<form action="/script/search/searchquery.asp" method="post" id="search" style="margin:0;padding:0;text-align:right;">
<P>
<label class="hidden" for="searchFor">Search</label>
<INPUT id="searchFor" style="HEIGHT: 15px" size="10" name="SearchString" title="Search" value="" /> <INPUT style="HEIGHT: 20px" type="submit" name="searchFor" value="Search" />
</P>
</form>

			</div><!-- end search_sub div-->
		</div><!-- end menuContainer div-->
	</div><!-- end GlobalNav id-->
	<a name="StartContent"> </a>
</div><!-- end header div -->