<div id="header">
	<div id="header_curve_wrapper">
		<div id="headerlc"> </div>
		<div id="headerrc"> </div>
	</div>	
	<div id="headertop"> 
		<a href="/index.shtml" title="DARS Home" ><img src="/images/DARSbanner.gif" alt="Department of Assistive and Rehabilitative Services" /></a>
	</div><!--end headertop -->
		<div id="skipnav">
			<a href="#StartContent" style="text-decoration: none;">Skip to Content</a></p></p>
			<a href="javascript:fontsizeup();" style="text-decoration: none;" title="Increase Font Size">Font Size +</a></p>
			<a href="javascript:fontsizedown();" style="text-decoration: none;" title="Decrease Font Size">Font Size -</a> 
		</div><!-- end skipnav -->
	<div id="GlobalNav">
		<div class="menuContainer">
			<ul class="mainMenu" id="navItem"> <!-- change back to name -->





				<li><a href="/services/index.shtml" class="navItem">Find Services</a>
					<ul class="navMenu">
						<li><a href="/drs/index.shtml" class="navItem">Rehabilitation Services</a></li>						
						<li><a href="/dhhs/index.shtml" class="navItem">Deaf and Hard of Hearing Services</a></li>
						<li><a href="/dbs/index.shtml" class="navItem">Blind Services</a></li>
						<li><a href="/ecis/index.shtml" class="navItem">Early Childhood Intervention Services</a></li>						
						<li><a href="/services/dds.shtml" class="navItem">Disability Determination Services</a></li>
						<li><a href="/services/agencyservices.shtml" class="navItem">Help for State Agencies</a></li>
						<li><a href="/services/personalattendants.shtml" class="navItem">Find a personal attendant</a></li>
						<li><a href="/edc/index.shtml" class="navItem">Employment &#38; Disability Connections&#47; </p>Medicaid Buy&#45;In</a></li>
                       				<li><a href="/stakeholders/autism/index.shtml" class="navItem">Autism Program</a></li>
						<li><a href="/supemp/index.shtml" class="navItem">Find a Supported Employment Provider</a></li>
					</ul>
				
				</li>
	





				<li><a href="/news/index.shtml" class="navItem">News &amp; Information</a>
					<ul class="navMenu">
						<li><a href="/about/index.shtml" class="navItem">About DARS</a></li>
						<li><a href="/announcements/index.shtml" class="navItem"> Announcements</a></li>
						<li><a href="/contact/index.shtml" class="navItem">Contact Us</a></li>
						<li><a href="/reports/index.shtml" class="navItem">Data &amp; Reports</a></li>
						<li><a href="/reports/financial.shtml" class="navItem">Financial and Budget Information</a></li>
						<li><a href="https://rm.accesshr.hhsc.state.tx.us/ENG/careerportal/default.cfm?szUniqueCareerPortalID=fbc767e0-795a-412f-8897-431b08f314e8" class="navItem">Jobs</a></li>
						<li><a href="/legislative/legislative.shtml" class="navItem">Legislative Updates</a></li>						
						<li><a href="/contact/visitor.shtml" class="navItem">Maps &amp; Visitor Information</a></li>
						<li><a href="/news/meetings.shtml" class="navItem">Meeting Notices</a></li>
						<li><a href="/publications/index.shtml" class="navItem">Publications</a></li>
						<li><a href="/stakeholders/index.shtml" class="navItem">Stakeholder Relations</a></li>
						</ul>
				</li>




				<li><a href="/rules/index.shtml" class="navItem">Rules &amp; Statutes</a>
					<ul class="navMenu">						
						<li><a href="/rules/index.shtml" class="navItem">Federal/State statutes</a></li>
						<li><a href="/rules/openrecords.shtml" class="navItem">Public Information</a></li>						
						<li><a href="/rules/sitepolicies.shtml" class="navItem">Site Policies</a></li>
					</ul>
				</li>



				<li><a href="/business/index.shtml" class="navItem">Business Information</a>
					<ul class="navMenu">
						<li><a href="/business/index.shtml" class="navItem">Doing Business with DARS</a></li>
						<li><a href="/business/contracts.shtml" class="navItem">Contracts</a></li>
						<li><a href="http://www.window.state.tx.us/comptrol/expendlist/expendlist.html" class="navItem">DARS Expenditures</a></li>
						<li><a href="/business/energy.shtml" class="navItem">Energy Consumption</a></li>
						<li><a href="/business/providers.shtml" class="navItem">Provider &amp; Contractor Information</a></li>
						<li><a href="/business/procurement.shtml" class="navItem">Procurement</a></li>
						<li><a href="/business/hub.shtml" class="navItem">Historically Underutilized Businesses</a></li>
						<li><a href="/business/grants.shtml">Grants/Funding Opportunities</a></li>
						<li><a href="http://www.window.state.tx.us/wherethemoneygoes">Where The Money Goes</a></li>
						<li><a href="/edc/grants/gvprogram.shtml">DARS Grants and Volunteer Program</a></li>
					</ul>
				</li>



				<li><a href="/arra/index.shtml" class="navItem">Stimulus (ARRA)</a>
					<ul class="navMenu">
						<li><a href="https://sao.fraud.state.tx.us/hotline.aspx" class="navItem">State Auditor's Fraud Hotline</a></li>
						<li><a href="/arra/rfp.shtml" class="navItem">Requests for Proposals</a></li>
						<li><a href="/arra/quarterly.shtml" class="navItem">Quarterly Reports</a></li>

<!--
						<li>DARS ARRA Plans</li>
						<li>Grant Awards</li>
						<li>DARS ARRA Contract Template</li>
						<li>Buy American/Buy Green</li>
						<li>Quarterly Reports (Accessible Version)</li>
						<li>State Weekly Reports</li>
-->

					</ul>
				</li>





			</ul>
			<div id="search_sub" style="vertical-align:middle;">
				<form action="/script/search/searchquery.asp" method="post" id="search" style="margin:0;padding:0;text-align:right;"><p style="font-size:.01em;"><label for="searchFor" title="Search for"></label>
					<input name="SearchString" type="text" size="10" id="searchFor"  style="/* \*/height:15px; */ " />
					<input name="searchFor" type="submit" value="Search" style="height:20px;" /></p>
				</form>
			</div><!-- end search_sub div-->
		</div><!-- end menuContainer div-->
	</div><!-- end GlobalNav id-->
	<a name="StartContent"> </a>
</div><!-- end header div -->